<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.11">
  <compounddef id="classtranslator__client_1_1exceptions_1_1ApiAttributeError" kind="class" language="Python" prot="public">
    <compoundname>translator_client::exceptions::ApiAttributeError</compoundname>
    <basecompoundref refid="classtranslator__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">translator_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">AttributeError</basecompoundref>
    <basecompoundref refid="classtranslator__client_1_1exceptions_1_1OpenApiException" prot="public" virt="non-virtual">translator_client.exceptions.OpenApiException</basecompoundref>
    <basecompoundref prot="public" virt="non-virtual">AttributeError</basecompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classtranslator__client_1_1exceptions_1_1ApiAttributeError_1ad5559f88a67e90f715e995f9bf926ff1" prot="public" static="no" mutable="no">
        <type></type>
        <definition>translator_client.exceptions.ApiAttributeError::path_to_item</definition>
        <argsstring></argsstring>
        <name>path_to_item</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="79" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="79" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classtranslator__client_1_1exceptions_1_1ApiAttributeError_1ab991648d023ce8a13f1370801daf5123" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def translator_client.exceptions.ApiAttributeError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Raised when an attribute reference or assignment fails.

Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="68" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="68" bodyend="85"/>
      </memberdef>
      <memberdef kind="function" id="classtranslator__client_1_1exceptions_1_1ApiAttributeError_1ab991648d023ce8a13f1370801daf5123" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def translator_client.exceptions.ApiAttributeError.__init__</definition>
        <argsstring>(self, msg, path_to_item=None)</argsstring>
        <name>__init__</name>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>msg</type>
          <defname>msg</defname>
        </param>
        <param>
          <type>path_to_item</type>
          <defname>path_to_item</defname>
          <defval>None</defval>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
<para><verbatim>Raised when an attribute reference or assignment fails.

Args:
    msg (str): the exception message

Keyword Args:
    path_to_item (None/list) the path to the exception in the
received_data dict
</verbatim> </para>        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="OpenAPI/tests/translator_client/translator_client/exceptions.py" line="68" column="1" bodyfile="OpenAPI/tests/translator_client/translator_client/exceptions.py" bodystart="68" bodyend="85"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1970">
        <label>translator_client.exceptions.OpenApiException</label>
        <link refid="classtranslator__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="1971" relation="public-inheritance">
        </childnode>
        <childnode refid="1971" relation="public-inheritance">
        </childnode>
      </node>
      <node id="1969">
        <label>translator_client.exceptions.ApiAttributeError</label>
        <link refid="classtranslator__client_1_1exceptions_1_1ApiAttributeError"/>
        <childnode refid="1970" relation="public-inheritance">
        </childnode>
        <childnode refid="1972" relation="public-inheritance">
        </childnode>
        <childnode refid="1970" relation="public-inheritance">
        </childnode>
        <childnode refid="1972" relation="public-inheritance">
        </childnode>
      </node>
      <node id="1971">
        <label>Exception</label>
      </node>
      <node id="1972">
        <label>AttributeError</label>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1974">
        <label>translator_client.exceptions.OpenApiException</label>
        <link refid="classtranslator__client_1_1exceptions_1_1OpenApiException"/>
        <childnode refid="1975" relation="public-inheritance">
        </childnode>
        <childnode refid="1975" relation="public-inheritance">
        </childnode>
      </node>
      <node id="1973">
        <label>translator_client.exceptions.ApiAttributeError</label>
        <link refid="classtranslator__client_1_1exceptions_1_1ApiAttributeError"/>
        <childnode refid="1974" relation="public-inheritance">
        </childnode>
        <childnode refid="1976" relation="public-inheritance">
        </childnode>
        <childnode refid="1974" relation="public-inheritance">
        </childnode>
        <childnode refid="1976" relation="public-inheritance">
        </childnode>
      </node>
      <node id="1975">
        <label>Exception</label>
      </node>
      <node id="1976">
        <label>AttributeError</label>
      </node>
    </collaborationgraph>
    <location file="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" line="67" column="1" bodyfile="OpenAPI/tests/editable_copies/translator_client/translator_client/exceptions.py" bodystart="67" bodyend="86"/>
    <listofallmembers>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiAttributeError_1ab991648d023ce8a13f1370801daf5123" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiAttributeError</scope><name>__init__</name></member>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiAttributeError_1ab991648d023ce8a13f1370801daf5123" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiAttributeError</scope><name>__init__</name></member>
      <member refid="classtranslator__client_1_1exceptions_1_1ApiAttributeError_1ad5559f88a67e90f715e995f9bf926ff1" prot="public" virt="non-virtual"><scope>translator_client::exceptions::ApiAttributeError</scope><name>path_to_item</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
